object Constants {
  val DB_USERNAME = "MYSQL_DB_USERNAME"
  val DB_PASSWORD = "MYSQL_DB_PASSWORD"
  val DB_HOST = "MYSQL_DB_HOST"
  val DB_PORT = "MYSQL_DB_PORT"
  val DB_DATABASE = "MYSQL_DB_DATABASE"
  val DB_TABLE = "MYSQL_DB_TABLE"
}
